- readme.md
I don't know if it's "awesome" but I haven't seen any Zig project do something like this yet, so might as well propose it.
> Add pure internal coding with Zig

- readme.md
Adds hazeycode/zig-alsa to the Audio section and hazeycode/brucelib to the Game tools and libraries section
> Add a couple of my projects

- readme.md
Self promotion: adding my simple Chip8 emulation library/executable.
> Added ChipZ to emulators section

- readme.md
> Add Zig Support for JetBrains IDEs

- readme.md
> libvlc-zig added

- readme.md
TOMLv1.0.0 parser and convert TOML to JSON.
> Add naneros/ztoml

- readme.md
A simple OS written in Zig following Philipp Oppermann's posts "Writing an OS in Rust".
> Add `rafaelbreno/zig-os`

- readme.md
Project: https://github.com/orhun/linuxwave
Demo: https://www.youtube.com/watch?v=SLiEuvDmo8M
I'm not sure if this should be added to "audio" or "other" so let me know if you want me to update the category.
Cheers!
> Add linuxwave

- readme.md
I suppose Ziglings ought to be here. Thanks! :-)
> Add ziglings to readme.md

- readme.md
> Zap - http server

- readme.md
> C/C++ libraries packaged for Zig

- readme.md
New C++ boost library ported to zig-pkg
> boost.context ported to zig-pkg

- readme.md
All being actively maintained.
> add cache.zig, zuckdb.zig and singleflight.zig

- readme.md
* ziglang libraries
* zig build-system port libraries
* new section - same idea in https://github.com/C-BJ/awesome-zig/issues/21
cc: @catdevnull
> Some libraries

- readme.md
I added two messaging libraries. (Disclaimer: I am the author of zzmq.)
Feel free to modify any of the changes.
Best Regards, Felix
> Add messaging libraries

- readme.md
- Added my CLI library, Cova, to the Parsers list.
> Add Cova to Parsers list

- readme.md
As noted on their GitHub readme, they've moved to CodeBerg
> Update ziglings exercises

- readme.md
Write super-fast AWS Lambda functions in Zig with ease.
> Add AWS Lambda runtime

- readme.md
Adding link for `zprob` library
> add pblischak/zprob

- readme.md
Add **loo-re/zini** in the **Parser** section
> Add loo-re/zini
